EE-2340: Fixed incorrect configurations in the Salesforce template
SecureAuthCorp/Configurations pull request #1009
Opened 2021-12-17 18:45 UTC by dcostaSA

The changes were made based on the configurations found in other templates, like the ones for Adobe and Dropbox

2021-12-17 18:49 UTC, dcostaSA commented
Do not merge this yet!
We have to get a confirmation on whether hints or other options have to be added to the fixed fields (like the url hints and other options found in the configurations of the other companies used as examples)

2021-12-20 17:52 UTC, khernan requested changes
the signSamlMessage property is still using "defaultValue": false
you should update it to "true".
Also i think that we must update the other templates to use defaultValue true as well
there are at least 72 templates that has set the value : "false"

2021-12-21 20:16 UTC, khernan approved these changes

2022-01-27 14:04 UTC, ejsecrist approved these changes

2022-01-27 16:27 UTC, merged